# The contents of this file is based on https://github.com/home-assistant/core/blob/dev/pyproject.toml

target-version = "py310"

# Line length configuration
line-length = 88

# Import sorting configuration
src = ["custom_components"]

[isort]
known-first-party = ["custom_components"]
force-single-line = true
lines-between-types = 1

select = [
    "B",   # flake8-bugbear
    "C",   # complexity
    "D",   # docstrings
    "E",   # pycodestyle
    "F",   # pyflakes/autoflake
    "I",   # isort
    "ICN", # import conventions
    "N",   # pep8-naming
    "PGH", # pygrep-hooks
    "PLC", # pylint
    "PLE", # pylint
    "PLR", # pylint
    "PLW", # pylint
    "RUF", # Ruff-specific rules
    "S",   # bandit
    "SIM", # simplify
    "T20", # flake8-print
    "TCH", # type-checking
    "TRY", # tryceratops
    "UP",  # pyupgrade
    "W",   # pycodestyle warnings
]

ignore = [
    "C901",  # Complex code
    "D203",  # 1 blank line required before class docstring
    "D213",  # Multi-line docstring summary should start at the second line
    "E731",  # do not assign a lambda expression, use a def
]

[per-file-ignores]
"custom_components/home_energy_hub/__init__.py" = ["D100"]
"custom_components/home_energy_hub/const.py" = ["D100"]

# Type checking configuration
type-checking = true
typecheck-on-save = true

[mccabe]
max-complexity = 12

[flake8-quotes]
quotes = "double"
docstring-quotes = "double"

[pep8-naming]
classmethod-decorators = ["classmethod", "validator", "root_validator"]

exclude = [
    "assets/",
]

[flake8-pytest-style]
fixture-parentheses = false

[pyupgrade]
keep-runtime-typing = true

[mccabe]
max-complexity = 25

