line-length = 88
target-version = "py310"
src = ["custom_components"]

[lint]
select = [
    "B",   # flake8-bugbear
    "C",   # complexity
    "D",   # docstrings
    "E",   # pycodestyle
    "F",   # pyflakes/autoflake
    "I",   # isort
    "ICN", # import conventions
    "N",   # pep8-naming
    "PGH", # pygrep-hooks
    "PLC", # pylint
    "PLE", # pylint
    "PLR", # pylint
    "PLW", # pylint
    "RUF", # Ruff-specific rules
    "S",   # bandit
    "SIM", # simplify
    "T20", # flake8-print
    "TCH", # type-checking
    "TRY", # tryceratops
    "UP",  # pyupgrade
    "W",   # pycodestyle warnings
]

ignore = [
    "C901",  # Complex code
    "D203",  # 1 blank line required before class docstring
    "D213",  # Multi-line docstring summary should start at the second line
    "E731",  # do not assign a lambda expression, use a def
]

[lint.per-file-ignores]
"custom_components/home_energy_hub/__init__.py" = ["D100"]
"custom_components/home_energy_hub/const.py" = ["D100"]

[lint.mccabe]
max-complexity = 12

[lint.flake8-quotes]
inline-quotes = "double"
multiline-quotes = "double"
docstring-quotes = "double"

[lint.pep8-naming]
classmethod-decorators = ["classmethod", "validator", "root_validator"]

[lint.flake8-pytest-style]
fixture-parentheses = false

[lint.pyupgrade]
keep-runtime-typing = true

[lint.isort]
known-first-party = ["custom_components"]
force-single-line = true
lines-between-types = 1