name: "Feature request"
description: "Suggest an idea or enhancement for the Home Energy Hub"
labels: "Feature+Request"

body:
- type: markdown
  attributes:
    value: |
      ## Proposing a Feature? 💡

      - **First**, search if a similar request has already been proposed. Let's avoid duplicates.
      - **Describe** the problem and solution in detail. It helps us understand your perspective and needs.

- type: dropdown
  attributes:
    label: "Integration Type 🔄"
    description: "Which integration would this feature apply to?"
    options:
      - "Seplos V2 BMS"
      - "GEO IHD"
      - "New Integration"
      - "Core Platform"
      - "Other (please specify)"
  validations:
    required: true
  
- type: dropdown
  attributes:
    label: "Connection Method 🌐"
    description: "How would this feature interact with devices?"
    options:
      - "USB-RS485 Serial"
      - "Telnet Serial"
      - "HTTP API"
      - "Multiple/All"
      - "Other (please specify)"
  validations:
    required: true

- type: textarea
  attributes:
    label: "Problem Description 🤔"
    description: "Is your feature request related to a problem? Please provide a clear description of what the problem is."
    placeholder: "I'm always frustrated when [...]"
  validations:
    required: true

- type: textarea
  attributes:
    label: "Proposed Solution 🛠️"
    description: "Describe the solution you'd like to see implemented. Be as detailed as possible."
  validations:
    required: true

- type: textarea
  attributes:
    label: "Alternatives Considered 🔄"
    description: "Have you thought of other ways to address this problem or similar features? Share them here."
  validations:
    required: false

- type: textarea
  attributes:
    label: "Additional context 📄"
    description: "Provide any other relevant details, context, or screenshots about the feature request. It helps us get a fuller picture."
  validations:
    required: false
