name: "Lint 2.0.0"

on:
  push:
    branches:
      - "2.0.0"
  pull_request:
    branches:
      - "2.0.0"

jobs:
  python-check:
    name: "Python Syntax Check"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@v4.1.1"

      - name: "Set up Python"
        uses: actions/setup-python@v5.0.0
        with:
          python-version: "3.11"

      - name: "Check Python syntax"
        run: |
          python3 -m py_compile custom_components/home_energy_hub/*.py
          python3 -m py_compile custom_components/home_energy_hub/connectors/*.py
          python3 -m py_compile custom_components/home_energy_hub/integrations/*.py
          python3 -m py_compile custom_components/home_energy_hub/integrations/geo_ihd/*.py
          python3 -m py_compile custom_components/home_energy_hub/integrations/seplos_v2/*.py