name: "Validate 2.0.0"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - "2.0.0"
  pull_request:
    branches:
      - "2.0.0"

jobs:
  hassfest:
    name: "Hassfest Validation"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@v4.1.1"

      - name: "Run hassfest validation"
        uses: "home-assistant/actions/hassfest@master"

  hacs:
    name: "HACS Validation"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@v4.1.1"

      - name: "Run HACS validation"
        uses: "hacs/action@main"
        with:
          category: "integration"
          ignore: "brands"